name: CI/CD - Go App with App Runner

on:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Rodar go fmt
        run: test -z "$(gofmt -l .)" || (echo "Código não formatado"; exit 1)

      - name: Rodar go vet
        run: go vet ./...

  tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Verificar go.mod/go.sum
        run: |
          go mod tidy
          git diff --exit-code || (echo "go.mod ou go.sum estão desatualizados"; exit 1)
